# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f950ba51c5d3f1625d51fc5621c131e714db4d60149cc024ad8ac2df96113748ec1105b8d35c2d2248a5a6b7071a7c33bd05bc5d6de03fb15843078e740ffa4c

test:
  secret_key_base: efe142760064e09ca205bb1cacfd4d1cfc5de911cdff78b0688a68b6574d499231494257f5d46d8621831321607ee82dba2f06b31b18f19c5fb233afb668bc1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
